services:
  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: bgutil-provider
    restart: unless-stopped
    networks:
      - downloader_net

  multi-downloader:
    image: ghcr.io/nikolainyegaard/multi-downloader:latest
    container_name: multi-downloader
    restart: unless-stopped
    environment:
      TZ: "Europe/Oslo"
    volumes:
      - ./data:/app/data:ro
    expose:
      - "8000"
    networks:
      - caddy_net
      - downloader_net
    depends_on:
      - bgutil-provider

  multi-downloader-admin:
    image: ghcr.io/nikolainyegaard/multi-downloader:latest
    container_name: multi-downloader-admin
    restart: unless-stopped
    environment:
      TZ: "Europe/Oslo"
      ADMIN_MODE: "1"
    volumes:
      - ./data:/app/data:rw
    expose:
      - "8000"
    networks:
      - caddy_net
      - downloader_net
    depends_on:
      - bgutil-provider

networks:
  caddy_net:
    external: true
  downloader_net:
